// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFhhd1sV7H7D_MrwkWDp0V7SKAxPehi8',
    appId: '1:757342741446:web:04da8e41a4fb216a0c48c7',
    messagingSenderId: '757342741446',
    projectId: 'cancu-50eb4',
    authDomain: 'cancu-50eb4.firebaseapp.com',
    databaseURL: 'https://cancu-50eb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cancu-50eb4.firebasestorage.app',
    measurementId: 'G-91DLX7NJF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpW8tU90ht-gtylkd-HwiJJwWBh97UleU',
    appId: '1:757342741446:android:0871c30492474e6a0c48c7',
    messagingSenderId: '757342741446',
    projectId: 'cancu-50eb4',
    databaseURL: 'https://cancu-50eb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cancu-50eb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyb6heghwIRUyz8eEGa3SsmVqiMhouq40',
    appId: '1:757342741446:ios:c5e7fd0cdbe2f3d90c48c7',
    messagingSenderId: '757342741446',
    projectId: 'cancu-50eb4',
    databaseURL: 'https://cancu-50eb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cancu-50eb4.firebasestorage.app',
    iosBundleId: 'com.example.caccuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyb6heghwIRUyz8eEGa3SsmVqiMhouq40',
    appId: '1:757342741446:ios:c5e7fd0cdbe2f3d90c48c7',
    messagingSenderId: '757342741446',
    projectId: 'cancu-50eb4',
    databaseURL: 'https://cancu-50eb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cancu-50eb4.firebasestorage.app',
    iosBundleId: 'com.example.caccuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFhhd1sV7H7D_MrwkWDp0V7SKAxPehi8',
    appId: '1:757342741446:web:df807468e967c8130c48c7',
    messagingSenderId: '757342741446',
    projectId: 'cancu-50eb4',
    authDomain: 'cancu-50eb4.firebaseapp.com',
    databaseURL: 'https://cancu-50eb4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cancu-50eb4.firebasestorage.app',
    measurementId: 'G-F8X559QW2G',
  );

}