final List<Map<String, dynamic>> defaultImages = [
  {'name': 'Cà phê', 'path': 'lib/img/icon/cafe.png'},
  {'name': 'Mỹ phẩm', 'path': 'lib/img/icon/cosmetics.png'},
  {'name': 'Đồ uống', 'path': 'lib/img/icon/drink.png'},
  {'name': 'Ăn uống', 'path': 'lib/img/icon/food.png'},
  {'name': 'Tiền điện', 'path': 'lib/img/icon/electric.png'},
  {'name': 'Tang lễ', 'path': 'lib/img/icon/funeral.png'},
  {'name': 'Internet', 'path': 'lib/img/icon/internet.png'},
  {'name': 'Đầu tư', 'path': 'lib/img/icon/invest.png'},
  {'name': 'Trẻ em', 'path': 'lib/img/icon/kid.png'},
  {'name': 'Học tập', 'path': 'lib/img/icon/learning.png'},
  {'name': 'Chi phí sinh hoạt', 'path': 'lib/img/icon/living_cost.png'},
  {'name': 'Tiết kiệm', 'path': 'lib/img/icon/save_money.png'},
  {'name': 'Mua sắm', 'path': 'lib/img/icon/shopping.png'},
  {'name': 'Giao thông', 'path': 'lib/img/icon/transpot.png'},
  {'name': 'Du lịch', 'path': 'lib/img/icon/travel.png'},
  {'name': 'Nước sinh hoạt', 'path': 'lib/img/icon/water.png'},
  {'name': 'Đám cưới', 'path': 'lib/img/icon/wedding.png'},
  {'name': 'Y tế', 'path': 'lib/img/icon/health.png'},
];
